export type events = {
	id: number;
	name: string;
	address: string;
	location: string;
	date: Date;
	time: string;
	description: string;
	going: boolean;
	type: string;
	organizer: string;
	capacity: number;
};

export const data: events[] = [
  {
    id: 1,
    name: "Summer Basketball Tournament",
    address: "671-8052 Aliquam Rd.",
    location: "Main Court A",
    date: new Date("Jul 6, 2025"),
    time: "12:12 AM",
    description: "elit. Nulla facilisi. Sed",
    going: true,
    type: "Basketball",
    organizer: "Auctor Ltd",
    capacity: 1280,
  },
  {
    id: 2,
    name: "Soccer League Finals",
    address: "671-8406 Fermentum Rd.",
    location: "Field 3",
    date: new Date("Jan 22, 2026"),
    time: "8:27 AM",
    description: "nunc. Quisque",
    going: false,
    type: "Soccer",
    organizer: "Aliquam Institute",
    capacity: 29976,
  },
  {
    id: 3,
    name: "Youth Swim Meet",
    address: "2978 Vestibulum Rd.",
    location: "Aquatic Center - Pool 1",
    date: new Date("Jan 15, 2025"),
    time: "6:36 PM",
    description: "cursus in, hendrerit consectetuer, cursus et, magna.",
    going: true,
    type: "Swimming",
    organizer: "Eget Volutpat Ornare Foundation",
    capacity: 21648,
  },
  {
    id: 4,
    name: "High School Volleyball Match",
    address: "830-7229 Morbi Road",
    location: "Gymnasium Court B",
    date: new Date("Jul 2, 2025"),
    time: "10:34 PM",
    description: "pede. Praesent eu dui. Cum sociis",
    going: true,
    type: "Volleyball",
    organizer: "Integer Vitae Nibh Associates",
    capacity: 10689,
  },
  {
    id: 5,
    name: "Community Tennis Doubles",
    address: "270-1499 Egestas Street",
    location: "Tennis Court #2",
    date: new Date("May 25, 2025"),
    time: "6:33 PM",
    description: "Donec est mauris, rhoncus id, mollis nec,",
    going: true,
    type: "Tennis",
    organizer: "Pellentesque Habitant Industries",
    capacity: 12777,
  },
  {
    id: 6,
    name: "Track & Field Invitational",
    address: "P.O. Box 754, 8638 Quis St.",
    location: "Athletic Field",
    date: new Date("Dec 11, 2025"),
    time: "12:10 AM",
    description: "tristique ac, eleifend",
    going: true,
    type: "Track & Field",
    organizer: "Amet Consulting",
    capacity: 28983,
  },
  {
    id: 7,
    name: "College Football Kickoff",
    address: "Ap #862-5174 Non, Street",
    location: "Stadium Section B",
    date: new Date("Apr 15, 2026"),
    time: "12:50 PM",
    description: "libero at auctor ullamcorper,",
    going: true,
    type: "Football",
    organizer: "Vulputate Risus A Corporation",
    capacity: 23873,
  },
  {
    id: 8,
    name: "Youth Baseball Scrimmage",
    address: "P.O. Box 485, 3525 Nisi. Avenue",
    location: "Diamond #4",
    date: new Date("Jul 1, 2025"),
    time: "3:38 AM",
    description: "et magnis dis",
    going: false,
    type: "Baseball",
    organizer: "Adipiscing PC",
    capacity: 2466,
  },
  {
    id: 9,
    name: "Charity Golf Classic",
    address: "P.O. Box 794, 882 Accumsan Avenue",
    location: "Green Hills Golf Club",
    date: new Date("Oct 30, 2024"),
    time: "12:11 PM",
    description: "lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor",
    going: false,
    type: "Golf",
    organizer: "Quam Vel PC",
    capacity: 17274,
  },
  {
    id: 10,
    name: "Esports LAN Tournament",
    address: "205-5001 Metus. Ave",
    location: "Gaming Center Room 201",
    date: new Date("Sep 7, 2025"),
    time: "11:55 AM",
    description: "eu tellus. Phasellus elit pede,",
    going: false,
    type: "Esports",
    organizer: "Massa Integer Limited",
    capacity: 15903,
  },
  // …continue similarly for events 11–20
];
